# Generated by Django 3.2 on 2021-10-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digilockerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentModel',
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='document',
            new_name='file',
        ),
    ]
