# Generated by Django 3.2 on 2021-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilockerapp', '0002_auto_20211007_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='title',
            field=models.TextField(),
        ),
    ]
